<a href="https://colab.research.google.com/github/DKorchagina/industrial-development-git-control-task/blob/main/Pearson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Корчагина Дарья, ИВТ-41БО
##Домашнее задание на 16.10.22 "Критерий Пирсона для простых гипотез: задания"

###Task 1
Сгенерировать 100 псевдослучайных чисел на отрезке [0; 4] (встроенной функцией
генерации псевдослучайных чисел). Проверить гипотезу о равномерном распределении на [0; 4].

In [ ]:
import numpy

random_float_array = numpy.random.uniform(0, 4, size=100)
random_float_array

array([1.02467529, 1.8366073 , 0.2765913 , 3.10824167, 2.15781129,
       3.31702362, 1.69756954, 3.79606869, 0.06529216, 2.0794501 ,
       2.1935581 , 0.01024969, 1.59476288, 3.50710878, 2.1605744 ,
       3.56330858, 0.53264684, 3.46646515, 3.22856443, 2.60879372,
       0.52018314, 3.55374168, 3.69747454, 2.04418744, 1.05033105,
       3.25330465, 3.08885327, 1.53838832, 3.88067029, 1.67916605,
       1.64056042, 2.76478948, 0.50309919, 0.8672515 , 2.5518368 ,
       2.53484842, 0.36425657, 0.60411252, 1.4213169 , 2.27554084,
       2.97916403, 2.47175396, 2.05831665, 1.18638767, 1.46562442,
       3.00038712, 1.65745997, 2.81330524, 3.83263305, 3.81439098,
       0.17936476, 2.08397066, 3.25913188, 2.84013871, 3.27560818,
       2.47666906, 2.1906086 , 1.42209451, 3.35394083, 1.34378189,
       3.15825656, 2.72751553, 1.2776279 , 1.85238408, 0.28289879,
       0.23738722, 0.17138061, 2.07251537, 0.34060044, 2.68693932,
       0.27275631, 0.60810756, 0.48077589, 2.80552839, 3.69471337,
       2.42198017, 3.87381058, 3.39923885, 2.77571946, 2.49613947,
       3.97107453, 1.22044207, 2.5403662 , 0.98725504, 1.44823109,
       0.89490352, 3.82573612, 2.48015223, 2.73459733, 2.41927142,
       2.13579949, 1.32341689, 1.08748225, 2.50533225, 3.16528923,
       0.47419168, 2.186726  , 2.4211191 , 0.71533579, 1.83910449])

H0 = {"датчик псевдослучайных чисел на отрезке [0;4] имеет равномерное распределение"}

интервалы: [0; 1), [1; 2), [2; 3), [3; 4], r =4.

In [ ]:
count_for_delta = {'delta1': len([item for item in random_float_array if item >=0 and item < 1]), 'delta2': len([item for item in random_float_array if item >=1 and item < 2]), 'delta3': len([item for item in random_float_array if item >=2 and item < 3]), 'delta4': len([item for item in random_float_array if item >=3 and item <= 4])}

In [ ]:
pi0 = {'delta1': 0.25, 'delta2': 0.25, 'delta3': 0.25, 'delta4': 0.25}

In [ ]:
calculate = {'i':[1, 2, 3, 4], 'ni': list(count_for_delta.values()), 'pi0': list(pi0.values())}

In [ ]:
import pandas

df = pandas.DataFrame.from_dict(calculate)

In [ ]:
df['npi0'] = df['pi0']*100
df['ni-npi0'] = df['ni'] - df['npi0']
df['pearson'] = df['ni-npi0']**2 / df['npi0']
df

   i  ni   pi0  npi0  ni-npi0  pearson
0  1  21  0.25  25.0     -4.0     0.64
1  2  21  0.25  25.0     -4.0     0.64
2  3  33  0.25  25.0      8.0     2.56
3  4  25  0.25  25.0      0.0     0.00

In [ ]:
summa_pearsona = sum(df['pearson'])
summa_pearsona

3.84

In [ ]:
x_krit = 7.8

In [ ]:
if summa_pearsona > x_krit:
  print("Нулевая гипотеза отвергается")
else:
  print("Нет оснований отвергнуть нулевую гипотезу")

Нет оснований отвергнуть нулевую гипотезу

###Task 2
Сгенерировать 400 псевдослучайных чисел на отрезке [0; 4] (встроенной функцией генерации псевдослучайных чисел), каждое возвести в квадрат. Проверить
гипотезу о равномерном распределении этих квадратов на [0; 16].

In [ ]:
random_float_array2 = numpy.random.uniform(0, 4, size=400)
random_float_array2 = [x**2 for x in random_float_array2]
random_float_array2

[0.4642455106972378,
 9.432872304273788,
 9.678093661730149,
 3.6014574180912264,
 11.031708609908943,
 0.20811740713525614,
 3.9192937956547405,
 11.511345219539102,
 3.6823148369818504,
 5.017041967593812,
 11.41015837238014,
 3.583348862972629,
 6.465168778184398,
 1.5601576237820647,
 0.8482773588784889,
 3.0936013860830185,
 12.942134441367335,
 0.19662092642071405,
 3.141445161190332,
 0.8994459651746701,
 0.5268087731631007,
 0.5836129388688379,
 1.79557465845291,
 14.29519055158047,
 4.772453526994226,
 0.7978906204290676,
 12.657437759721589,
 0.4565243826687547,
 2.069208477685406,
 0.3439707242683714,
 0.7804167970003099,
 5.618874684317527,
 3.473466259033366,
 3.1995590813643915,
 7.3090686631700255,
 1.7491384578906004,
 0.719285355561841,
 0.11905455788540158,
 12.847448158055164,
 9.552193581911714,
 14.989302754875462,
 8.909639242000317,
 0.8072181469820715,
 0.5567335023002425,
 1.420410033034576,
 0.26796840446702264,
 5.802138384210582,
 0.08153597953347559,
 0.4751252425594438,
 6.089139988415346,
 12.942928635845764,
 5.655523333674799,
 3.178620667254063,
 9.89782649868811,
 14.26023822749753,
 2.612918579298044,
 14.412935776200744,
 8.813783295660194,
 9.075658447747227,
 2.3952584746409196,
 0.6167478811488186,
 0.004839802922552959,
 1.0016695282366375,
 0.11588546622021685,
 8.923002689250824,
 2.4482349023233376,
 15.64247994621746,
 6.383532394884152,
 1.6037953603376618,
 1.6238464860729067,
 0.9654458330796436,
 3.879343444020344,
 11.317837793461246,
 1.0562520093086367,
 14.728855682450877,
 0.5004008555716645,
 15.270172058833635,
 12.510016691307358,
 1.7181711994561817,
 9.445803116872563,
 2.1289515707459756,
 0.09417650455162493,
 2.150258402905808,
 12.479253669314522,
 12.643550500203649,
 9.68859664059771,
 5.223528061171151,
 10.388924841163497,
 0.9641047000742504,
 3.946148592723651,
 3.483710896701551,
 0.05306230240903613,
 0.34841121098964023,
 3.33613874874273,
 0.7622613970617649,
 5.390542308178969,
 1.4004074885036186,
 14.216950762881375,
 1.419557818016566,
 7.756394070742619,
 0.3475749366302757,
 1.402967531255434,
 0.38193488958074584,
 3.379693974957181,
 3.118701946861578,
 4.477329660005076,
 0.01776906931960274,
 0.2123021952398442,
 0.17539767121580224,
 1.456390434352068,
 4.9824496777528475,
 1.9570085677251083,
 0.11348470454502106,
 0.0002532053801299303,
 13.327834302246684,
 13.515618133305153,
 8.166785112224359,
 0.7356052805063874,
 0.03211842928341312,
 1.8528593206155426,
 9.13863298144941,
 8.877396086736052,
 4.021696249678425,
 4.103165363187884,
 1.0378563823493336,
 1.8198459429443514,
 5.234597085310841,
 6.339399044010293,
 1.0820496476842676,
 2.1278133774199075,
 14.338976852924684,
 10.328668256085317,
 0.7602644044433746,
 10.765715499619102,
 3.5405373769194477,
 11.690538681577173,
 0.4411417046078226,
 12.148528754439914,
 10.827085568035358,
 1.820833261886168,
 2.666041069926865,
 9.375747358382561,
 3.1671151819027092,
 4.599636798785066,
 0.5470772450524068,
 3.127659071292793,
 6.929059535599547,
 13.992189222046095,
 9.769839232427465,
 1.4335780264970222,
 8.762204335549574,
 0.119649474139426,
 10.112027325941094,
 1.505405429509317,
 0.9507947785665686,
 11.289803815099756,
 0.5797053181257064,
 3.932679376378816,
 11.593853770562891,
 0.0258145873283465,
 2.312267246831792,
 14.55277688753915,
 4.68704101877867,
 1.0508363402715672,
 6.916229834315673,
 0.6748637314682091,
 1.8012251445308975,
 4.180415298840078,
 0.02388467175908337,
 6.2872041811392325,
 3.6740493738938804,
 5.222434086724395,
 1.1808936489801274,
 7.789058817701713,
 0.5858864039671354,
 3.5123037181716983,
 3.2074993241135483,
 5.000260088944237,
 0.041130114248684416,
 10.326565399028462,
 7.352585193693128,
 0.08182319385841408,
 0.8201295275831899,
 0.11008132482727398,
 15.717070683870922,
 1.5281615385701417,
 15.45716336424391,
 2.391916609397647,
 0.06477425934868637,
 13.648909993409664,
 12.046353873536363,
 11.415578770516433,
 1.7215441854658078,
 4.651498495951264,
 10.41132234753424,
 2.5796675825330904,
 15.572548681586019,
 5.109746504267578,
 0.9627247742074213,
 9.870478369059555,
 13.439779894729368,
 12.719252514665222,
 0.803229028170336,
 12.266290692500512,
 0.037087246149691076,
 0.04905846843621511,
 8.479244729283074,
 10.60652046151037,
 8.998025281839416,
 9.506891741954885,
 15.208409403529222,
 0.009736288679480511,
 10.25583067777726,
 0.042786343421524126,
 3.308700870269817,
 0.5663757144897733,
 0.14000023487627167,
 13.129125191871005,
 4.9566654442025015,
 2.2281164872007633,
 14.97225818847911,
 5.385051025954756,
 1.9374009750465306,
 0.02859062850169211,
 0.017843499627539998,
 1.9073978343364824,
 1.8130257876345033,
 6.460351549233969,
 10.050142133691555,
 2.647295923186163,
 11.454253689161384,
 9.96076254479097,
 0.04137927417662382,
 15.893716588261054,
 10.635482887081672,
 0.22847671620371582,
 10.582823154798245,
 9.737091024561437,
 1.510005635022733,
 10.17328727331163,
 0.0032732373389869267,
 5.481917738138342,
 1.0707905271897586,
 0.41833275927528946,
 2.1902204010756754,
 8.094661982645999,
 13.958800163983145,
 8.425042095256671,
 1.58131709219859,
 0.31501852581939377,
 0.03880213239918342,
 11.373357303000164,
 0.5931276099272272,
 13.018608851157921,
 1.5417744288656086,
 2.875605441117228,
 9.774359427849827,
 3.7652390981353943,
 1.8897791714346919,
 0.02832941100857411,
 1.8327761586420546,
 12.599003706934566,
 5.177321647087673,
 0.9699850394134887,
 0.009747951928092562,
 1.3903013888820084,
 13.1572896170788,
 0.7494003767038647,
 2.1150991239615826,
 7.158751802542901e-05,
 2.5971008336666928,
 10.32698723854404,
 0.024621038239464783,
 10.886804614931325,
 3.1092327249142566,
 7.633947256231792,
 0.8830611288715314,
 0.682042743550117,
 4.94896446120144,
 1.2079658536390556,
 0.9627981295950966,
 14.200748931436056,
 3.353231071095058,
 0.9977931208243371,
 5.439260287173827,
 9.150627359480167,
 10.65481187406474,
 2.2630445029901547,
 10.766751870173676,
 0.622447990068154,
 14.3709037307867,
 4.025545064617134,
 0.9644429469839408,
 7.337445415725568,
 11.619759934339289,
 15.032996049549652,
 8.690627279148664,
 5.8146480966599885,
 2.762663227874473,
 0.31425537482479676,
 0.9774559134234208,
 0.7341063997809931,
 10.634010861427857,
 6.644580968185302,
 11.357870467307054,
 3.041415746328353,
 14.573633454865636,
 0.01948886591014416,
 14.670349485896663,
 9.282099121232164,
 4.29120082376214,
 0.06556000601536313,
 3.959180842526473,
 5.888734804660032,
 0.45618738083087274,
 2.1664868863618563,
 9.669373022943985,
 0.061107267155629336,
 1.587886148522091,
 11.105626910994346,
 1.2702455072766528,
 7.154519566157154,
 0.03220726224090873,
 1.2518216305006853,
 1.4110643106197756,
 4.9002712973247595,
 5.73835475002624,
 5.677212389431734,
 0.5639955307358256,
 3.429372443520592,
 6.943391173555712,
 3.54593452585329,
 2.4306190001132126,
 10.150504981956153,
 8.854387503596026,
 5.203026001676975,
 0.009984468692648222,
 9.534883672527734,
 15.133556928559644,
 6.570379637480761,
 1.6984503938639608,
 12.101326851755527,
 0.27991757673737017,
 5.989167000224407,
 2.0770559410969915,
 2.8637287420873614,
 2.398981174728866,
 0.8228530759546585,
 8.526605912370375,
 4.7063938856652605,
 15.624544275498838,
 0.00989423743810854,
 8.699244423587311,
 4.274128283171767,
 0.41671129837382725,
 14.639708132323188,
 1.477289440302249,
 2.168818212373773,
 1.4283540595545643,
 0.000218801174275518,
 9.39229941642526,
 3.99136563701118,
 8.861883393233613,
 4.843949149874172,
 0.1581355968086376,
 5.052797966848972,
 2.2263083807266892,
 2.0644193477888018,
 3.2098464536208837,
 0.5669008834301849,
 6.069451554421234,
 1.7923245464839739,
 5.341470308888972,
 1.73825567836208,
 1.9443195021545532,
 6.91595184077724,
 4.226124790966139,
 6.24017380771657,
 0.31673435397486666,
 6.185657864184164,
 1.845185747926083,
 8.885500597181684,
 6.865394083777016,
 2.69926333006272,
 5.768217038865659,
 0.02144227071101938,
 10.378312595162532,
 7.290912895069673,
 2.6536031962980355,
 3.330263834245495,
 0.20524488361775958,
 14.961848689101448,
 2.3391232168349387,
 0.6680215326268572,
 9.154079486278436,
 0.16830681713122356,
 1.6950063859573363,
 12.282359967985098,
 2.6309511716118053,
 2.404955255396909]

интервалы: [0; 5), [5; 10), [10; 13), [13; 16], r =4.

In [ ]:
count_for_delta = {'delta1': len([item for item in random_float_array2 if item >=0 and item < 5]), 
    'delta2': len([item for item in random_float_array2 if item >=5 and item < 10]),
    'delta3': len([item for item in random_float_array2 if item >=10 and item < 13]), 
    'delta4': len([item for item in random_float_array2 if item >=13 and item <= 16])}
pi0 = {'delta1': 5/16, 'delta2': 5/16, 'delta3': 3/16, 'delta4': 3/16}
calculate = {'ni': list(count_for_delta.values()), 'pi0': list(pi0.values())}
df2 = pandas.DataFrame.from_dict(calculate)
df2

    ni     pi0
0  235  0.3125
1   84  0.3125
2   47  0.1875
3   34  0.1875

In [ ]:
df2['npi0'] = df2['pi0']*400
df2['ni-npi0'] = df2['ni'] - df2['npi0']
df2['pearson'] = df2['ni-npi0']**2 / df2['npi0']
df2

    ni     pi0   npi0  ni-npi0    pearson
0  235  0.3125  125.0    110.0  96.800000
1   84  0.3125  125.0    -41.0  13.448000
2   47  0.1875   75.0    -28.0  10.453333
3   34  0.1875   75.0    -41.0  22.413333

In [ ]:
summa_pearsona2 = sum(df2['pearson'])
x_krit2 = 7.8
if summa_pearsona2 > x_krit2:
  print("Нулевая гипотеза отвергается")
else:
  print("Нет оснований отвергнуть нулевую гипотезу")

Нулевая гипотеза отвергается

###Task 3
Для выборки из задания 2 проверить гипотезу о том, что эти квадраты распределены с функцией распределения

In [ ]:
df3 = df2[['ni']]
df3

    ni
0  235
1   84
2   47
3   34

In [ ]:
import math
df3.loc[:, 'pi0'] = [math.sqrt(5)/4, math.sqrt(10)/4 - math.sqrt(5)/4, math.sqrt(13)/4 - math.sqrt(10)/4, 1 - math.sqrt(13)/4]
df3['npi0'] = df3['pi0']*400
df3['ni-npi0'] = df3['ni'] - df3['npi0']
df3['pearson'] = df3['ni-npi0']**2 / df3['npi0']
df3

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

    ni       pi0        npi0    ni-npi0   pearson
0  235  0.559017  223.606798  11.393202  0.580506
1   84  0.231552   92.620968  -8.620968  0.802422
2   47  0.110818   44.327362   2.672638  0.161142
3   34  0.098612   39.444872  -5.444872  0.751597

In [ ]:
summa_pearsona3 = sum(df3['pearson'])
x_krit3 = 7.8
if summa_pearsona3 > x_krit3:
  print("Нулевая гипотеза отвергается")
else:
  print("Нет оснований отвергнуть нулевую гипотезу")

Нет оснований отвергнуть нулевую гипотезу